void parser(char*);
char* filterLine(char*);
char* getNewLine(char*);
struct tokenType filterToken(struct tokenType);
void vars();
void block();
void stats();
void stat();
void mstat();
void in();
void out();
