void parser(char*);
char* filterLine(char*);
char* getNewLine(char*);
void filterToken(struct tokenType);
void error(int,char*);
void getNewToken();
void program();
void vars();
void block();
void stats();
void stat();
void mstat();
void in();
void out();
